<?php

namespace TravelBundle\Repository;

/**
 * PackagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackagesRepository extends \Doctrine\ORM\EntityRepository
{
}
