<?php

namespace TravelBundle\Repository;

/**
 * TorderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorderRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOrderByTravelId($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT t FROM TravelBundle:Travel t WHERE t.id = :id')->setParameter("id", $id);
        return $query->getResult();
    }

     public function getPackageByTravelId($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p FROM TravelBundle:Packages p WHERE p.travel_id = :id')->setParameter("id", $id);
        return $query->getResult();
    }

    public function getAmountByTravelId($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT a FROM TravelBundle:Amount a WHERE a.travel_id = :id')->setParameter("id", $id);
        return $query->getResult();
    }

        public function getDurationByTravelId($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT d FROM TravelBundle:Duration d WHERE d.travel_id = :id')->setParameter("id", $id);
        return $query->getResult();
    }



}
