<?php

namespace TravelBundle\Repository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderByTravelId($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT t FROM TravelBundle:Travel t WHERE t.id = :id')->setParameter("id", $id);
        return $query->getResult();
    }


}
